### ISSUE TITLE
Python Direct Intergrator in Mitsuba 3

### ISSUE THREAD

**Issue by andiac** [mitsuba-renderer/mitsuba-tutorials#5]
Hi! I am trying to replicate the Mitsuba 2's [direct_integrator tutorial](https://github.com/mitsuba-renderer/mitsuba2/blob/master/docs/examples/03_direct_integrator/direct_integrator.py) in Mitsuba 3 and [this](https://gist.github.com/andiac/3565092f27279ca9bf8722c9be6627e7) is my replication. 

There is an error when executing 

```
active_b &= dr.neq(emitter, 0.0)
```

Any help with it? Thanks.

**Comment by wjakob** [comment]
That line doesn't really make sense 🤔. Try `None` instead of `0.0`

**Comment by wjakob** [comment]
Generally this kind Mitsuba 2 code can be expressed more compactly because of implicit masking. If an instance in an instance array equals `None`, Mitsuba 3 will just not do the call for that lane and return zeroes. Closing the issue. If you have further problems, please open a discussion post unless you are sure that you are dealing with a Mitsuba bug (in which case you would need to upload a full reproducer)

**Comment by andiac** [comment]
Thanks!
