### ISSUE TITLE
About Multiple Importance Sampling

### ISSUE THREAD

**Issue by andiac** [mitsuba-renderer/mitsuba-tutorials#7]
Hello! I have got a question about [the implementation of the direct integrator](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/integrators/direct.cpp).

According to the [PBR book](https://www.pbr-book.org/3ed-2018/Light_Transport_I_Surface_Reflection/Direct_Lighting), the [MIS estimator](https://www.pbr-book.org/3ed-2018/Monte_Carlo_Integration/Importance_Sampling#sec:importance-sampling) is 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11074066/182039700-a7c84cda-5be4-45c8-8879-1fcfe9b890c4.png">
, p_f and p_g in the denominators can be probability density functions (pdf) of "Sampling the BSDF" and "Sampling the light source". 

However, in the `direct.cpp` I can not find such a denominator. Line 168 of `direct.cpp` is
```
result[active_e] += mis * bsdf_val * emitter_val;
```
and lines 200-203 are
```
result[active_b] +=
                    bsdf_val * emitter_val *
                    mis_weight(bs.pdf * m_frac_bsdf, emitter_pdf * m_frac_lum) *
                    m_weight_bsdf;
```
where I think we have to multiply them with 1/p, where p is the pdf of the BSDF or the emitter. Could you please tell me what's wrong with my current understanding?

([Here](https://gist.github.com/andiac/00c8251330473e4c601dd3dbcef1141f) is my replication of the Multiple Importance Sampling. Without the denominators, the result looks fine. But the formula tells us there should be a denominator. )

**Comment by merlinND** [comment]
Hello @andiac,

In Mitsuba, we use the convention that all `sample_...` functions return the _sampling weight_, rather than the evaluated value. The sampling weight is already equal to the value divided by the pdf, which is why they don't appear in the integrator.
I understand that the `_val` suffix in the variable name is confusing w.r.t. this!

https://github.com/mitsuba-renderer/mitsuba3/blob/07e1ff8853b3b31bda7ac4784e3a253215bf2bfe/include/mitsuba/render/bsdf.h#L310-L315

**Comment by andiac** [comment]
Hi @merlinND! 

I see; the same thing happens in `scene.sample_emitter_direction(...)`. This makes all the things clear! Thanks a lot for your help!!
